### PR TITLE
Feature/auto update submodule

### PR DESCRIPTION
**Pull request by likeuntomurphy**
This will ensure the `roles` submodule is up to date before a `up`, `provision` or `reload` command.

It will not (yet) automatically re-provision a Vagrant box if changes are detected to `Vagrantfile`, `group_vars/all` or `provision.yml`. I have a plan of attack in mind if either of you think it’s necessary, too (Alex G. did).

This builds on #27, so the only relevant changes for this PR are in https://github.com/fostermadeco/development-standard/commit/80288be263144686ff8dedb7f2474a1a89232bac.

### CODE REVIEW

**Comment by StevenMHernandez** [comment]
I wish it was a bit easier to see all pull requests require reviews.

Does this remove the need for either of the `git submodule` notes in the readme? https://github.com/fostermadeco/development-standard#etc

**Comment by likeuntomurphy** [comment]
It does make that section obsolete (in fact, as it stands, it’s totally inaccurate). But I am leaning more towards a different approach here, which I would like to try out and put this PR on pause.

**Comment by likeuntomurphy** [comment]
@StevenMHernandez I’ve made the changes I wanted to make for this functionality. `git submodule update` is now added to a post-merge git hook and run whenever you pull (and when you pull this change).

It also displays a message advising you to re-provision your VM if any configuration file changes — `group_vars/all`, `Vagrantfile` or the `ansible/roles` object in the superproject’s repository. I initially wanted to actually do the re-provision automatically, but it entered an infinite loop.

I removed the (inaccurate) advice from the `README` file and did not replace it with anything. Given the amount of confusion surrounding the submodule, I did not see any advantage to even mentioning it  at all now that the updating happens automatically.

**Comment by likeuntomurphy** [comment]
This is also no longer dependent on #27

**Comment by StevenMHernandez** [comment]
This was a bit confusing to get through. I didn't realized ORIG_HEAD means "original head" as opposed to "origin head". 

Also, I wish there were steps that I could use to test all assumptions. But I think this looks right to me.

**Comment by likeuntomurphy** [comment]
Apparently we do need the `--init` appended to `git submodule update` for when a repo is first cloned. I am testing that now.

**Comment by smaida** [comment]
Repo archived. Won't merge.

**Pull request closed without merging**
