### PR TITLE
Fix invalid box metadata URLs

### LINKED ISSUE #26: vagrantcloud.com fix generates error with Vagrant 2.0.3+
`Message: RuntimeError: can't modify frozen String`

### PR DESCRIPTION
**Pull request by likeuntomurphy**
This introduces an idea I have been playing around with for a couple of weeks — using an Ansible playbook to check the state of your local system before proceeding with the Vagrant command.

The immediate issue addressed with this initial task is that the fix introduced in PR #10 actually causes an error with Vagrant 2.0.3 and higher, because `Vagrant::DEFAULT_SERVER_URL` has been made immutable. So this fixes #26.

To test, before adding these changes to a project, remove the change from #10 from Vagrantfile. Find a box that has an old URL by running `grep atlas.hashicorp.com ~/.vagrant.d/boxes/*/metadata_url`, and then identify a project that uses that box. When you run `vagrant up` or `vagrant reload`, you should see an error message when Vagrant checks for the latest version of that box saying the URL cannot be found.

At this point, incorporate these changes. Rerunning the command should not show the error, because the URLs will be updated automatically. Further, `grep atlas.hashicorp.com ~/.vagrant.d/boxes/*/metadata_url` should not return any results thereafter.

### CODE REVIEW

**Comment by StevenMHernandez** [comment]
Hmm, I can't seem to get the initial problem to show up to test this solution. 

It sounds like any of our projects should have this same issue, but are there any specific projects where I would see this issue? We can either talk about this off-github or perhaps having a sample project where the issue exists would be useful.

**Comment by likeuntomurphy** [comment]
It would actually be specific to your local Vagrant installation — if, somehow, you did not download any boxes with `atlas.hashicorp.com` URLs, then you would never experience this problem. So, switching projects won’t in itself help.

I would say you can try swapping the domain names in one of the box `metadata_url` files from `vagrantcloud.com` back to `atlas.hashicorp.com` — but in my experience, Vagrant seemed to cache available box data somewhere else, too. This had the effect of telling me an update was available for, say, the `ubuntu/trusty64` after one of my various solutions worked, even though the `ubuntu-VAGRANTSLASH-trusty64/metadata_url` file clearly included the wrong URL. I didn’t really feel like diagnosing why or figuring out where the cached data was stored. But maybe simply changing a domain name will work for you.

**Comment by likeuntomurphy** [comment]
@StevenMHernandez Would you be satisfied with reverting a metadata URL in one of the `metadata_url` files (e.g., `~/.vagrant.d/boxes/bento-VAGRANTSLASH-ubuntu-16.04/metadata_url`) and checking if it changes?

I know that Nina is running version 2.0.3 and is having to effectively change and `assume-unchanged` the Vagrantfile in the FM site project to get around the error without potentially causing a regression for other project developers. So it would be great to get this out so I can at least update that project.

**Comment by StevenMHernandez** [comment]
Yes it does update the url in the file.

However, I am not sure if it is fixing the error because I can't quite figure out the exact steps that I would use to reproduce the error. (Or maybe I am missing the warning when running `vagrant reload`). You mentioned some cache that I probably have on my system which prevents me from seeing this error. If that is the case, wouldn't anyone else with the older url (atlas.hashicorp.com) also be cached? Would this be an issue?

If changing the url is all that needs to happen, then the code does what it says it will do and as such could be merged. I just can't verify the results.

**Comment by likeuntomurphy** [comment]
Ok, I am going to hazard merging this. 🤞

**Pull request merged**
